# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
# ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
# Portions of this makefile
# Copyright (C) 1993 - 1995  Microsoft Corporation.  All Rights Reserved.
#
# Remainder of this makefile
# Copyright (C) 1999 Bill Buckels. All Rights Reserved.
#
# Processor independent makefile

# Nmake macros for building Windows 32-Bit apps
!include <win32.mak>

PROJ = Splitit
EXEPATH = ..\

all: $(PROJ).exe

# Define project specific macros
PROJ_OBJS  = Splitit.obj
BASE_OBJS  =
EXTRA_LIBS = LZ32.LIB
GLOBAL_DEP = Splitit.h
RC_DEP     = Splitit.rc



# Inference rule for updating the object files
.c.obj:
  $(cc) $(cdebug) $(cflags) $(cvars) $*.c

# Build rule for resource file
$(PROJ).res: $(PROJ).rc $(RC_DEP)
    $(rc) $(rcflags) $(rcvars) /fo $(PROJ).res $(PROJ).rc

# Build rule for EXE
#    $(link) $(linkdebug) $(guilflags) \

$(PROJ).EXE: $(BASE_OBJS) $(PROJ_OBJS) $(PROJ).res
    $(link) $(guilflags) \
    $(BASE_OBJS) $(PROJ_OBJS) $(PROJ).res $(guilibs) $(EXTRA_LIBS) \
    -out:$(PROJ).exe $(MAPFILE)
    del *.obj
    del *.res
    move $(PROJ).exe ..

# Rules for cleaning out those old files
clean:
    del *.bak *.pdb *.obj *.res *.exp *.map *.sbr *.bsc
